language: php

sudo: false

env:
  global:
    - SYMFONY_VERSION="2.8.*"
    - RUN_PHPCS="no"
    - COMPOSER_FLAGS=""

matrix:
  include:
    - php: 5.5
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*"
    - php: 5.6
      env: RUN_PHPCS="yes" SYMFONY_VERSION="3.1.*"
    - php: 7.0
    - php: 7.0
      env: SYMFONY_VERSION="3.2.*"
    - php: 7.0
      env: SYMFONY_VERSION="3.3.*@dev"
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer require --no-update symfony/yaml:${SYMFONY_VERSION}
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/; fi;
