language: php

env:
  global:
    - SYMFONY_VERSION="2"

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: SYMFONY_VERSION="3"
    - php: 7.0
    - php: 7.0
      env: SYMFONY_VERSION="3"
    - php: hhvm
  allow_failures:
    - php: hhvm

before_script:
  # TODO - Remove @dev when Symfony 3.0 is tagged stable
  - if [ "SYMFONY_VERSION" == "3" ]; then composer require --no-update symfony/yaml:3.0@dev; fi
  - composer update

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/
